apiVersion: apps/v1
kind: Deployment
metadata:
  name: plasma-donor-application-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: plasma-donor-application
  template:
    metadata:
      labels:
        app: plasma-donor-application

    spec:
      containers:
        - name: plasma-donor-application
          image: us.icr.io/plasma_donor_ns/plasma
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
